### ISSUE TITLE
sbt.ResolveException: unresolved dependency: com.projectseptember#freek_2.11;0.6.7: not found

### ISSUE THREAD

**Issue by epiphyllum** [calvinlfer/free-monad-coproduct-example#2]
can not pull this dependency. 

could you please give me a hint on how to set my build.sbt for this dependency?

my build.sbt is as follow:

name := "free-monad-coproduct-example"

version := "1.0"

scalaVersion := "2.11.8"

```scala
lazy val `free-monad-coproduct-example` =
  (project in file("."))
    .settings(Seq(addCompilerPlugin("com.milessabin" % "si2712fix-plugin_2.11.8" % "1.2.0")))

resolvers += Resolver.jcenterRepo
// resolvers += Resolver.bintrayRepo("projectseptemberinc", "maven")

libraryDependencies ++= {
  Seq(
    "org.typelevel"             %% "cats"     % "0.8.1",
    "com.projectseptember"      %% "freek"    % "0.6.7"
  )
}
```

**Comment by epiphyllum** [comment]
```
 ~/workspace/scala/freek-prog/ [master*] sbt clean
[info] Loading project definition from /Users/hary/workspace/scala/freek-prog/project
[info] Set current project to free-monad-coproduct-example (in build file:/Users/hary/workspace/scala/freek-prog/)
[success] Total time: 0 s, completed 2017-4-19 14:21:11
 ~/workspace/scala/freek-prog/ [master*] sbt update
[info] Loading project definition from /Users/hary/workspace/scala/freek-prog/project
[info] Set current project to free-monad-coproduct-example (in build file:/Users/hary/workspace/scala/freek-prog/)
[info] Updating {file:/Users/hary/workspace/scala/freek-prog/}free-monad-coproduct-example...
[info] Resolving com.projectseptember#freek_2.11;0.6.7 ...
[warn] 	module not found: com.projectseptember#freek_2.11;0.6.7
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.projectseptember/freek_2.11/0.6.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/projectseptember/freek_2.11/0.6.7/freek_2.11-0.6.7.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.projectseptember/freek_2.11/0.6.7/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.projectseptember/freek_2.11/0.6.7/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.projectseptember#freek_2.11;0.6.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.projectseptember:freek_2.11:0.6.7 (/Users/hary/workspace/scala/freek-prog/build.sbt#L15-21)
[warn] 		  +- free-monad-coproduct-example:free-monad-coproduct-example_2.11:1.0
sbt.ResolveException: unresolved dependency: com.projectseptember#freek_2.11;0.6.7: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
```

**Comment by calvinlfer** [comment]
That seems really odd, have you tried resolving the dependencies on a different network to see whether maybe your network is blocking JCenter?

**Comment by calvinlfer** [comment]
Also did 
```sbt
resolvers += Resolver.bintrayRepo("projectseptemberinc", "maven")
``` 
do anything for you?
I updated the project to use the latest stable version of Scala (2.12.2) as of today (2017-04-19) and updated to the current version of FreeK.
